(load "lib.ss")
(define (count-increasing l)
  (apply + (map (lambda (p) (if (< (car p) (cadr p)) 1 0)) (zip l (cdr l)))))
(define (a input) (count-increasing (numbers input)))
(define (b input) (count-increasing (map (partial apply +) (window 3 (numbers input)))))
