(load "lib.scm")
(define input (input))
(define (count-increasing l)
  (apply + (map (lambda (p) (if (< (car p) (cadr p)) 1 0)) (zip l (cdr l)))))
(display (count-increasing (numbers input)))
(newline)
(display (count-increasing (map (partial apply +) (window 3 (numbers input)))))